# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

prox <- function(z, gam, del) {
    .Call(`_OMME_prox`, z, gam, del)
}

magging <- function(B, Q, AE, ce, AI, ci) {
    .Call(`_OMME_magging`, B, Q, AE, ce, AI, ci)
}

admm <- function(dims, usex, B, Phi1, Phi2, Phi3, resp, penalty, kappa, usekappa, lambda, nlambda, makelamb, lambdaminratio, penaltyfactor, reltol, maxiter, steps, alg, bound) {
    .Call(`_OMME_admm`, dims, usex, B, Phi1, Phi2, Phi3, resp, penalty, kappa, usekappa, lambda, nlambda, makelamb, lambdaminratio, penaltyfactor, reltol, maxiter, steps, alg, bound)
}

maglas <- function(dims, usex, B, Phi1, Phi2, Phi3, resp, penalty, kappa, usekappa, lambda, nlambda, makelamb, lambdaminratio, penaltyfactor, steps) {
    .Call(`_OMME_maglas`, dims, usex, B, Phi1, Phi2, Phi3, resp, penalty, kappa, usekappa, lambda, nlambda, makelamb, lambdaminratio, penaltyfactor, steps)
}

